### ISSUE TITLE
set up a release protocol / checklist (see BIDS specs for ideas)

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS#116]
for example I forgot to update the version.txt in the last release

**Comment by Remi-Gau** [comment]
- [ ] create a dedicated branch for the release candidate from `dev`
- [ ] update `version.txt`
- [ ] add PR with INFRA (test, CI...)
- [ ] fix any remaining failing CI (test, markdown and code listing)
- [ ] ensure the doc is up to date
- [ ] make sure the doc builds correctly and fix any error
- [ ] merge to master
- [ ] create a tagged release

**Comment by Remi-Gau** [comment]
Added here: https://github.com/cpp-lln-lab/.github/blob/main/release_protocol.md
